language: go

go:
  - 1.0
  #- 1.0.1 1.0.1 is currently not running tests on Travis CI. Until multi-CI support is enabled, golang gophers pinned to backwards compatible 1.0.1 should be careful about running package generics, before testing it locally yourselves.
  - 1.0.2
  - 1.0.3
  - 1.1
  - 1.1.1
  - 1.1.2
  - 1.2
  - 1.2.1
  - 1.2.2
  - 1.3
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.4
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.5
  - 1.5.1
  - 1.5.2
  - 1.5.3
  - 1.5.4
  - 1.6
  - 1.6.1
  - 1.6.2
  - 1.6.3
  - 1.7
  - 1.7.1
  - tip
